site_name: Confidential Cloud
site_url: https://docs.confidentialcloud.io

site_description: >-
  Confidential Cloud is CanaryBit’s solution for 
  Businesses and Public Authorities that are willing to collaborate 
  with sensitive data and algorithms, and in need of a hardware-encrypted 
  execution environment protected from unauthorized access.
site_author: CanaryBit AB
copyright: >-
  Copyright © 2022 CanaryBit AB

repo_url: https://github.com/canarybit

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  palette:
    scheme: canarybit

extra_css:
  - stylesheets/canarybit.css

plugins:
  - search

nav:
  - 'Overview': 'index.md'
  - LEARN:
    - 'Architecture': 'architecture.md' 
  - TRY:
    - 'Login / Signup ⧉': 'http://confidentialcloud.io'
    - 'X.509 Certificate': x509_cert.md
  - CONNECT:
    - 'Book a Demo ⧉': 'https://www.canarybit.eu/book-a-demo/'
    - 'Support ⧉': 'https://canarybit.eu'
    - 'Blog ⧉': 'https://canarybit.eu/blog'
    - 'About us ⧉': 'https://www.canarybit.eu/team'


  