site_name: Confidential Cloud
site_url: https://docs.confidentialcloud.io
site_description: >-
  Confidential Cloud is CanaryBit’s solution for 
  Businesses and Public Authorities that are willing to collaborate 
  with sensitive data and algorithms, and in need of a hardware-encrypted 
  execution environment protected from unauthorized access.
site_author: CanaryBit AB
copyright: >-
  Developed by <a href="https://www.canarybit.eu" target="_blank">CanaryBit</a> 

repo_url: https://github.com/canarybit
repo_name: "/canarybit"

edit_uri: ""

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  palette:
    scheme: canarybit
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections

extra:
  social:
    - icon: material/web
      link: https://www.canarybit.eu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canarybit/

extra_css:
  - stylesheets/canarybit.css
        
plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - OVERVIEW: 
    - 'Intro': 'index.md'
    - 'Architecture': 'architecture.md'
    - 'Infrastructure': 'infrastructure.md'
    - 'Workflow': 'workflow.md'
    #- 'Encryption': []
    #- 'Security': []
    - 'Compliance': 'compliance.md'
    #- 'Legal': []
    #- 'Roadmap': []

  - REQUIREMENTS:
    - 'X.509 Certificate': 'x509_certificate.md'

  - USE:       
    - 'Create Account ⧉': https://demo.confidentialcloud.io/signup" target="_blank
    - Multi-Party Collaboration:
      - 'Login': http://demo.confidentialcloud.io" target="_blank
      #- 'Register your asset': []
      #- 'Start a collaboration': []
      #- 'Run an Enclave': []
      #- 'Collect results': []
      #- 'Collect attestation': []
      #- 'Collect audit logs': []
    - Secure Applications:
      - 'Confidential VMs' : ''
      - 'Confidential Containers': ''
      - 'Confidential AI' : ''
    - Secure Infrastructure:
      - 'Orchestration' : 'tower.md'
      - 'Verification' : 'inspector.md'


  - 'Support ⧉': https://canarybit.eu" target="_blank
  - 'Book a Demo ⧉': https://www.canarybit.eu/book-a-demo/" target="_blank
  - 'Blog ⧉': https://canarybit.eu/blog" target="_blank  