site_name: Confidential Cloud
site_url: https://docs.confidentialcloud.io
site_description: >-
  Confidential Cloud is CanaryBit’s solution for 
  Businesses and Public Authorities that are willing to collaborate 
  with sensitive data and algorithms, and in need of a hardware-encrypted 
  execution environment protected from unauthorized access.
site_author: CanaryBit AB
copyright: >-
  Developed by <a href="https://www.canarybit.eu" target="_blank">CanaryBit</a> © 2022 

repo_url: https://github.com/canarybit
repo_name: "/canarybit"

edit_uri: ""

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  palette:
    scheme: canarybit
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: material/web
      link: https://www.canarybit.eu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canarybit/

extra_css:
  - stylesheets/canarybit.css
        
plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Overview': 'index.md'
  - LEARN:
    - 'Architecture': 'architecture.md'
    - 'Infrastructure': 'infrastructure.md'
    - 'Workflow': 'workflow.md'
    #- 'Encryption': []
    #- 'Security': []
    - 'Compliance': 'compliance.md'
    #- 'Legal': []
    #- 'Roadmap': []

  - USE:
    #- 'Login / Signup ⧉': http://confidentialcloud.io" target="_blank
    - 'X.509 Certificate': 'x509_certificate.md'
    #- 'Add your Dataset / Application': []
    #- 'Start a Collaboration': []
    #- 'Request Access': []
    #- 'Run an Enclave': []
    #- 'Collect the Result': []
    #- 'Collect the Attestation': []
    #- 'Collect the Audit Logs': []

  - CONNECT:
    - 'Book a Demo ⧉': https://www.canarybit.eu/book-a-demo/" target="_blank
    - 'Support ⧉': https://canarybit.eu" target="_blank
    - 'Blog ⧉': https://canarybit.eu/blog" target="_blank
    - 'About us ⧉': https://www.canarybit.eu/team" target="_blank
  