site_name: Confidential Cloud
site_url: https://docs.confidentialcloud.io
site_description: >-
  CanaryBit Confidential Cloud is a virtual infrastructure security solution for 
  Businesses and Public Authorities that are willing to collaborate 
  with sensitive data and algorithms, and in need of a hardware-encrypted 
  execution environment protected from unauthorized access.
site_author: Canary Bit AB
copyright: >-
  Developed by <a href="https://www.canarybit.eu" target="_blank">CanaryBit</a> 

#repo_url: https://github.com/canarybit
#repo_name: "/canarybit"

edit_uri: ""

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  palette:
    - scheme: canarybit
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    #- navigation.tabs
    
    
extra:
  social:
    - icon: material/web
      link: https://www.canarybit.eu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canarybit/

extra_css:
  - stylesheets/canarybit.css
        
plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Overview: 'overview.md'
  - 'Create an Account ⧉': https://canarybit-production.auth.eu-north-1.amazoncognito.com/signup?client_id=54g4h9tpulnnkmhivgn5nipjki&response_type=code&scope=email+openid+profile&redirect_uri=https%3A%2F%2Fdocs.confidentialcloud.io%2F" target="_blank
  - Requirements:
    - 'Hardware': 'requirements/hardware.md'
    - 'Virtualization Platform': 'requirements/virtualization.md'
    - 'Operating Systems': 'requirements/operating-systems.md'
    - 'Containers': 'requirements/containers.md'
    #- 'Infrastructure': 'infrastructure.md'
    #- 'Workflow': 'workflow.md'
    #- 'Encryption': []
    #- 'Security': []
    #- 'Legal': []


  - Products & Tools:
    - 'TOWER': './products/tower.md'
    - 'INSPECTOR': './products/inspector.md'
    - 'SURVEYOR': './products/surveyor.md'
    #- 'STUDIO': './products/studio.md'

  - --- : []
  - 'Roadmap': []
  - 'Customer Support ⧉': https://canarybit.eu" target="_blank
 