site_name: Confidential Cloud
site_url: https://docs.confidentialcloud.io
site_description: >-
  CanaryBit Confidential Cloud is a digital infrastructure security suite for 
  Businesses and Public Authorities that are willing to collaborate 
  with sensitive data and algorithms, and in need of a hardware-encrypted 
  execution environment protected from unauthorized access.
site_author: Canary Bit AB
copyright: >-
  <iframe src="https://confidentialcloud.status.phare.io/embed-badges/live-status?align=start&background-light=f5f5f5&text-light=000000&background-dark=171717&text-dark=ffffff" width="190" height="30" loading="lazy" frameborder="0" scrolling="no" style="color-scheme: light dark;"></iframe>
  <br>
  Copyright © <a href="https://www.canarybit.eu" target="_blank">Canary Bit AB</a>

#repo_url: https://github.com/canarybit
#repo_name: "/canarybit"

edit_uri: ""

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  palette:
    - scheme: canarybit
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.path
    - navigation.top

extra:
  social:
    - icon: material/web
      link: https://www.canarybit.eu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canarybit/

extra_css:
  - stylesheets/canarybit.css
        
plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      url_download: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      # For a full list of supported emojis: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Welcome!: 'index.md'
  - Why Confidential Cloud: 'overview.md'
  - Requirements:
    - 'Overview': 'requirements.md'
    - 'Hardware': 'requirements/hardware.md'
    - 'Virtualization': 'requirements/virtualization.md'
    - 'Operating Systems': 'requirements/operating-systems.md'
    - 'Containers': 'requirements/containers.md'
    #- 'Encryption': []
    #- 'Security': []
    #- 'Legal': []

  - Products:
    - 'TOWER': './products/tower.md'
    - 'INSPECTOR': './products/inspector.md'
    - 'SURVEYOR': './products/surveyor.md'
  - Tools:
    - 'CanaryBit CLI': './tools/cli.md'

  - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . : []

  - 'Sign up': https://canarybit-production.auth.eu-north-1.amazoncognito.com/signup?client_id=54g4h9tpulnnkmhivgn5nipjki&response_type=code&scope=email+openid+profile&redirect_uri=https%3A%2F%2Fdocs.confidentialcloud.io%2F" target="_blank
  - 'Contact Support ⧉': https://www.canarybit.eu/contact" target="_blank